led mod = new Date(document.lastModified)
let month = mod.getMonth();
let date = mod.getDate();
let year = mod.getfullYear();
let hour = mod.getHours();
let min = mod.getMinutes();
let sec = mod.getSeconds();
let modified = "Last Updated: " + month + "/" + date + "/" + year + " " + hour + ":" + min + ":" + sec
document.getElementById("modified").textContent = modified